apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: searchpes.project.openubl
spec:
  group: project.openubl
  scope: Namespaced
  names:
    plural: searchpes
    singular: searchpe
    kind: Searchpe
    shortNames:
      - sp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: Searchpe is the Schema for the searchpes API.
          properties:
            spec:
              type: object
              properties:
                html:
                  type: string
#                externalAccess:
#                  type: object
#                  description: Controls external Ingress/Route settings.
#                  properties:
#                    enabled:
#                      type: boolean
#                      description: If set to true, the Operator will create an Ingress
#                        or a Route pointing to Searchpe.
#                    host:
#                      type: string
#                      description: If set, the Operator will use value of host for Ingress/Route
#                        host instead of default value searchpe.local for ingress and automatically
#                        chosen name for Route
#                    tlsTermination:
#                      type: string
#                      description: TLS Termination type for the external access. Setting
#                        this field to "reencrypt" will terminate TLS on the Ingress/Route
#                        level. Setting this field to "passthrough" will send encrypted
#                        traffic to the Pod. If unspecified, defaults to "reencrypt". Note,
#                        that this setting has no effect on Ingress as Ingress TLS settings
#                        are not reconciled by this operator. In other words, Ingress TLS
#                        configuration is the same in both cases and it is up to the user
#                        to configure TLS section of the Ingress.
#                externalDatabase:
#                  type: object
#                  description: "Controls external database settings. Using an external
#                     database requires providing a secret containing credentials as well
#                     as connection details. Here's an example of such secret: \n     apiVersion:
#                     v1     kind: Secret     metadata:         name: searchpe-db-secret
#                     \        namespace: searchpe     stringData:         POSTGRES_DATABASE:
#                     <Database Name>         POSTGRES_EXTERNAL_ADDRESS: <External Database
#                     IP or URL (resolvable by K8s)>         POSTGRES_EXTERNAL_PORT: <External
#                     Database Port>         # Strongly recommended to use <'Searchpe CR
#                     Name'-postgresql>         POSTGRES_HOST: <Database Service Name>         POSTGRES_PASSWORD:
#                     <Database Password>         # Required for AWS Backup functionality
#                     \        POSTGRES_SUPERUSER: true         POSTGRES_USERNAME: <Database
#                     Username>      type: Opaque \n Both POSTGRES_EXTERNAL_ADDRESS and
#                     POSTGRES_EXTERNAL_PORT are specifically required for creating connection
#                     to the external database. The secret name is created using the following
#                     convention:       <Custom Resource Name>-db-secret \n For more information,
#                     please refer to the Operator documentation."
#                  properties:
#                    type: object
#                    enabled:
#                      type: boolean
#                      description: If set to true, the Operator will use an external database.
#                        pointing to Keycloak.
#                instances:
#                  type: integer
#                  description: Number of Searchpe instances. Default is 1.
#                postgresDeploymentSpec:
#                  type: object
#                  description: Resources (Requests and Limits) for PostgresDeployment.
#                  properties:
#                    resources:
#                      type: object
#                      description: Resources (Requests and Limits) for the Pods.
#                      properties:
#                        limits:
#                          type: object
#                          description: 'Limits describes the maximum amount of compute
#                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
#                          additionalProperties:
#                            anyOf:
#                              - type: integer
#                              - type: string
#                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
#                            x-kubernetes-int-or-string: true
#                        requests:
#                          type: object
#                          description: 'Requests describes the minimum amount of compute
#                            resources required. If Requests is omitted for a container,
#                            it defaults to Limits if that is explicitly specified, otherwise
#                            to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
#                          additionalProperties:
#                            anyOf:
#                              - type: integer
#                              - type: string
#                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
#                            x-kubernetes-int-or-string: true
#                profile:
#                  type: string
#                  description: Profile used for controlling Operator behavior. Default
#                    is empty.
#                storageClassName:
#                  type: string
#                  description: Name of the StorageClass for Postgresql Persistent Volume
#                    Claim
#                unmanaged:
#                  type: boolean
#                  description: When set to true, this Keycloak will be marked as unmanaged
#                    and will not be managed by this operator. It can then be used for
#                    targeting purposes.
#            status:
#              type: object
#              description: SearchpeStatus defines the observed state of Searchpe.
#              properties:
#                credentialSecret:
#                  type: string
#                  description: The secret where the admin credentials are to be found.
#                internalURL:
#                  type: string
#                  description: Service IP and Port for in-cluster access to the searchpe
#                    instance.
#                message:
#                  type: string
#                  description: Human-readable message indicating details about current
#                    operator phase or error.
#                phase:
#                  type: string
#                  description: Current phase of the operator.
#                ready:
#                  type: boolean
#                  description: True if all resources are in a ready state and all work
#                    is done.
#                secondaryResources:
#                  type: object
#                  additionalProperties:
#                    items:
#                      type: string
#                    type: array
#                  description: 'A map of all the secondary resources types and names created
#                    for this CR. e.g "Deployment": [ "DeploymentName1", "DeploymentName2"
#                    ].'
#                version:
#                  type: string
#                  description: Version of Searchpe running on the cluster.
#              required:
#                - credentialSecret
#                - internalURL
#                - message
#                - phase
#                - ready
#                - version
