apiVersion: v1
kind: Service
metadata:
  name: {name}-keycloak-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: db
    tackle: {name}
